name: M3 — Reverse Conversion (.af→.met)
description: Tracking issue for M3 (Reverse Conversion (.af→.met)) — prefilled checklist
  from roadmap.final.md.
title: M3 — Reverse Conversion (.af→.met)
labels:
- milestone:M3
- area:reverse-conversion
- area:planner
- docs
- tests
body:
- type: textarea
  id: milestone_body
  attributes:
    label: Milestone issue body (prefilled)
    description: This field is prefilled so you can click Submit without typing. Edit
      as needed.
    value: "# M3 — Reverse Conversion (.af→.met)\n\n## Goal\nImplement the `.af→.met`\
      \ conversion workflow that uses the existing `mapping.yaml` to determine destination\
      \ paths within `MET_SOURCE_DIR`, validates mapping fields strictly, builds Plan/Preview,\
      \ invokes MetaF to produce `.met` files into staging, archives existing destination\
      \ `.met` files before overwrite and publishes new `.met` outputs via atomic\
      \ replace.\n\n## In Scope\n- Load and strictly validate `mapping.yaml` and ensure\
      \ required fields for `.af→.met` are present; fail fast if missing or invalid.\n\
      - Build Plan and Preview enumerating `.met` destination writes and side effects;\
      \ ensure determinism similar to M2.\n- Invoke MetaF per active mapping entry\
      \ into staging.\n- On approval, archive any existing destination `.met` using\
      \ `before_overwrite` naming.\n- Publish `.met` outputs into `MET_SOURCE_DIR`\
      \ via atomic temp‑then‑replace.\n- Apply Plan snapshot integrity checks, conflict\
      \ classification and run exclusivity lock (shared with M2).\n- Archive retention\
      \ enforcement after run completion.\n\n## Out of Scope\n- Bootstrapping MetaF.\n\
      - `.met→.af` conversion flows and Git operations.\n- Repair mapping and relink\
      \ logic.\n- Logging and hardening features.\n\n## Milestone checklist\n\n###\
      \ Acceptance criteria (DoD)\n- [ ] Reverse conversion pipeline produces correct\
      \ `.met` files in `MET_SOURCE_DIR` and archives any overwritten destinations.\n\
      - [ ] Mapping validation rejects missing or invalid fields and surfaces stable\
      \ error codes.\n- [ ] Plan/Preview for reverse flows enumerates all writes and\
      \ side effects.\n- [ ] Archive retention enforcement runs after reverse conversions.\n\
      - [ ] AT‑0015, AT‑0016, AT‑0028, AT‑0029 pass.\n\n### Exit artifacts\n- [ ]\
      \ Reverse conversion pipeline code and tests.\n- [ ] Updated documentation for\
      \ reverse conversion flows.\n- [ ] Test report demonstrating AT‑0015, AT‑0016\
      \ and cross‑plan tests.\n- [ ] Changelog entry summarizing reverse conversion\
      \ support.\n- [ ] Archive audit notes.\n\n## Links / evidence\n- Spec sections:\
      \ \n- Roadmap section: \n- Related issues/PRs: \n\n## Notes / decisions\n"
  validations:
    required: true
- type: textarea
  id: blockers
  attributes:
    label: Blockers / risks
    description: What could stop this milestone? Include mitigation if known.
    placeholder: '- Blocker:

      - Risk:

      - Mitigation:'
  validations:
    required: false
- type: textarea
  id: pr_links
  attributes:
    label: PR links / commits
    description: Add links to PRs or commit SHAs implementing this milestone work.
    placeholder: '- PR:

      - Commit:'
  validations:
    required: false
