name: M4 — Mapping Repair & Relink
description: Tracking issue for M4 (Mapping Repair & Relink)
title: M4 — Mapping Repair & Relink
labels:
- milestone:M4
- area:repair
- area:relink
- docs
- tests
body:
- type: textarea
  id: milestone_body
  attributes:
    label: Progress Checklist
    description: What needs to be completed for this milestone?
    value: "# M4 — Mapping Repair & Relink\n\n## Goal\nImplement workflows to repair\
      \ the mapping file when the fingerprint of `MET_SOURCE_DIR` drifts and to relink\
      \ mapping entries when `.af` files are moved or renamed. This milestone updates\
      \ the fingerprint, deterministically activates or retires items, enforces invariants,\
      \ writes `mapping.yaml` transactionally, and allows the user to locate or skip\
      \ missing `.af` files.\n\n## In Scope\n- Detect `MET_SOURCE_ROOT_FINGERPRINT`\
      \ mismatch at run start and block conversion until repair is performed.\n- Implement\
      \ Repair Mapping workflow: compute new fingerprint, rescan `MET_SOURCE_DIR`,\
      \ set item states to `active` or `retired`, update `MET_REL` and retire timestamps,\
      \ enforce invariants, and write `mapping.yaml` transactionally; support cancel\
      \ without writes.\n- Implement Relink workflow: when referenced `AF_REL` is\
      \ missing or unmapped `.af` files are present, search by size and hash; if exactly\
      \ one match, update `AF_REL`; otherwise prompt user to Locate or Skip; restrict\
      \ Locate selections to `AF_REPO_DIR`.\n- Update Plan/Preview engine to include\
      \ Repair and Relink outcomes in its display.\n\n## Out of Scope\n- Conversions\
      \ (`.met→.af` and `.af→.met`) themselves.\n- Bootstrap and logging hardening.\n\
      - Modifying naming or sanitization algorithms.\n\n## Milestone checklist\n\n\
      ### Acceptance criteria (DoD)\n- [ ] Repair Mapping detects fingerprint drift,\
      \ shows preview of activations/retirements and writes updated `mapping.yaml`\
      \ only on approval.\n- [ ] Relink workflow matches missing entries by size and\
      \ hash; user can locate within `AF_REPO_DIR` or skip.\n- [ ] Canceling Repair\
      \ Mapping or Relink produces no writes.\n- [ ] AT‑0017 and AT‑0018 pass.\n\n\
      ### Exit artifacts\n- [ ] Repair Mapping module and test report.\n- [ ] Relink\
      \ module and test report.\n- [ ] Updated `mapping.yaml` documentation.\n- [\
      \ ] Changelog entry describing repair and relink capabilities.\n- [ ] Decision\
      \ log noting activation/retirement rules.\n\n## Links / evidence\n- Spec sections:\
      \ \n- Roadmap section: \n- Related issues/PRs: \n\n## Notes / decisions\n"
  validations:
    required: true
- type: textarea
  id: blockers
  attributes:
    label: Blockers / risks
    description: What could stop this milestone? Include mitigation if known.
    placeholder: '- Blocker:

      - Risk:

      - Mitigation:'
  validations:
    required: false
- type: textarea
  id: pr_links
  attributes:
    label: PR links / commits
    description: Add links to PRs or commit SHAs implementing this milestone work.
    placeholder: '- PR:

      - Commit:'
  validations:
    required: false
