name: M5 — Observability, Hardening & Release
description: Tracking issue for M5 (Observability, Hardening & Release)
title: M5 — Observability, Hardening & Release
labels:
- milestone:M5
- area:hardening
- area:release
- docs
- tests
body:
- type: textarea
  id: milestone_body
  attributes:
    label: Progress Checklist
    description: What needs to be completed for this milestone?
    value: "# M5 — Observability, Hardening & Release\n\n## Goal\nFinalize the LIGHTNING\
      \ project by implementing determinism and reproducibility, robust logging and\
      \ error handling, transactional writes for generated files, UI performance optimizations\
      \ and upgrade/rollback support. This milestone also runs all acceptance tests\
      \ and prepares release notes. Only when all acceptance tests pass and documentation\
      \ is complete is the project considered done.\n\n## In Scope\n- Implement canonical\
      \ hashing for `MET_ID`, `AF_SHA256` and `METAF_BUNDLE_SHA` using SHA‑256 and\
      \ ensure deterministic encoding for generated files (`mapping.yaml`, workspace\
      \ files) with LF line endings.\n- Ensure all generated files are written transactionally\
      \ via temp file then atomic replace within their target directories.\n- Add\
      \ detailed logging to bootstrap and run workflows, redacting secrets and sensitive\
      \ tokens.\n- Surface stable error codes in the `LIGHTNING_{CATEGORY}_{NNNN}`\
      \ format for all user‑visible failures.\n- Provide a comprehensive error taxonomy\
      \ and exit code table as developer documentation.\n- Optimize UI responsiveness\
      \ during scanning and execution (finish implementation of REQ‑0801).\n- Ensure\
      \ upgrades do not corrupt persisted data and document supported upgrade and\
      \ rollback steps.\n- Produce upgrade and migration notes, release notes and\
      \ changelog entries.\n- Run the entire suite of acceptance tests and ensure\
      \ `REQ-1001` is satisfied.\n\n## Out of Scope\n- New feature development or\
      \ changes to workflows and mapping logic.\n- Additional integrations or optional\
      \ enhancements beyond Appendix E.\n\n## Milestone checklist\n\n### Acceptance\
      \ criteria (DoD)\n- [ ] Canonical hashing and transactional write modules integrated\
      \ and unit tested.\n- [ ] Logging outputs redact sensitive data and error codes\
      \ follow `LIGHTNING_{CATEGORY}_{NNNN}` format.\n- [ ] UI performance metrics\
      \ meet responsiveness goals during scanning and conversions.\n- [ ] Upgrade,\
      \ migration and rollback plans documented and validated.\n- [ ] Release notes,\
      \ upgrade guides, changelog and test report completed.\n- [ ] All acceptance\
      \ tests AT‑0001 through AT‑0030, AT‑9000 and AT‑9001 pass, satisfying REQ‑1001.\n\
      \n### Exit artifacts\n- [ ] Determinism modules and hashing tests.\n- [ ] Logging\
      \ and error handling framework documentation.\n- [ ] Performance tuning report.\n\
      - [ ] Release notes, upgrade instructions and rollback strategy.\n- [ ] Comprehensive\
      \ acceptance test report.\n- [ ] Roadmap change log updated. 1. Ensure backup\
      \ of `config.yaml`, `mapping.yaml` and archives. 2. Install new version of LIGHTNING.\
      \ 3. On first run, migrate any data formats using forward‑compatible upgrade\
      \ routines (REQ‑0203). 4. Verify `METAF_BUNDLE_SHA` remains valid; if not, re‑bootstrap\
      \ MetaF. 5. Run regression tests covering acceptance tests to confirm compatibility.\
      \ 1. Ensure backups of `config.yaml`, `mapping.yaml` and archives are available.\
      \ 2. Uninstall the new version and reinstall the previous release. 3. Restore\
      \ backed‑up configuration and mapping files. 4. Delete any archives created\
      \ by the failed upgrade.\n\n## Links / evidence\n- Spec sections: \n- Roadmap\
      \ section: \n- Related issues/PRs: \n\n## Notes / decisions\n"
  validations:
    required: true
- type: textarea
  id: blockers
  attributes:
    label: Blockers / risks
    description: What could stop this milestone? Include mitigation if known.
    placeholder: '- Blocker:

      - Risk:

      - Mitigation:'
  validations:
    required: false
- type: textarea
  id: pr_links
  attributes:
    label: PR links / commits
    description: Add links to PRs or commit SHAs implementing this milestone work.
    placeholder: '- PR:

      - Commit:'
  validations:
    required: false
