name: "M3 — Reverse Conversion (.af→.met)"
description: "Implement reverse conversion workflow with plan/preview, overwrite archiving and atomic publish into MET_SOURCE_DIR."
title: "M3 — Reverse Conversion (.af→.met)"
labels:
  - "milestone:M3"
  - "area:reverse-conversion"
  - "area:planner"
  - "tests"
  - "docs"
body:
  - type: markdown
    attributes:
      value: |
        ## Goal
        Implement the `.af→.met` reverse conversion workflow using the existing `mapping.yaml`.  
        This milestone strictly validates the mapping fields for reverse flows, builds a deterministic Plan and Preview enumerating
        `.met` destination writes and side effects, invokes MetaF to generate `.met` files into staging, archives any existing
        destination `.met` using the `before_overwrite` naming, and publishes the new `.met` outputs into `MET_SOURCE_DIR` via atomic
        replace.  The workflow shares run exclusivity and plan integrity checks with M2 and enforces archive retention after completion.

  - type: textarea
    id: context
    attributes:
      label: Context / Links
      description: Link spec sections, roadmap sections, prior issues/PRs, and any relevant notes.
      placeholder: |
        - Spec: docs/spec.final.md§8.3,§7.3,§7.4,§9.3
        - Roadmap: docs/roadmap.md§5.1–5.11 (M3)
        - Related: <ISSUE_OR_PR_LINKS>
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Scope

        ### In
        - **Mapping validation**: load `mapping.yaml` and validate required fields for reverse conversion; reject missing or invalid fields and fail fast.
        - **Plan & Preview**: build a Plan and Preview enumerating destination `.met` writes and side effects; ensure determinism similar to M2.
        - **Conversion pipeline**: invoke MetaF per active mapping entry into staging.
        - **Overwrite archiving**: before publishing each `.met` output, archive any existing destination using the `before_overwrite` naming rules.
        - **Publish**: publish staged `.met` outputs into `MET_SOURCE_DIR` via atomic temp‑then‑replace; apply conflict classification and run lock reuse; enforce Plan snapshot integrity checks.
        - **Archive retention**: enforce archive retention and cap rules after the run completes.

        ### Out
        - Bootstrapping MetaF (M1) and forward conversion (`.met→.af`) flows (M2).
        - Repair mapping and relink (M4).
        - Git staging/commit operations (reverse flows do not involve Git).
        - Logging/error hardening and final release tasks (M5).

  - type: checkboxes
    id: execution
    attributes:
      label: Execution checklist
      description: Check as implementation items are completed.
      options:
        - label: "Implement strict validation of `mapping.yaml` for reverse conversion; reject missing or invalid fields"
        - label: "Build deterministic Plan capturing input snapshot and intended `.met` writes"
        - label: "Generate Preview enumerating destination writes and side effects"
        - label: "Invoke MetaF per active mapping entry into a staging directory"
        - label: "Archive any existing destination `.met` before overwrite using `before_overwrite` naming"
        - label: "Publish staged `.met` outputs into `MET_SOURCE_DIR` via atomic replace"
        - label: "Revalidate plan snapshot and enforce run exclusivity lock; abort on drift"
        - label: "Enforce archive retention and cap after reverse conversion"
        - label: "Add unit/integration tests for reverse conversion flows, including validation, plan stability and overwrite archiving"

  - type: checkboxes
    id: dod
    attributes:
      label: Definition of Done
      description: Check as items are satisfied.
      options:
        - label: "Reverse conversion pipeline produces correct `.met` files in `MET_SOURCE_DIR` and archives any overwritten destinations"
        - label: "Mapping validation rejects missing or invalid fields with clear error codes"
        - label: "Plan/Preview for reverse flows enumerates all writes and side effects and is deterministic"
        - label: "Archive retention enforcement runs after reverse conversions"
        - label: "Milestone‑scoped acceptance tests pass (AT‑0015, AT‑0016, AT‑0028, AT‑0029)"

  - type: checkboxes
    id: exit_artifacts
    attributes:
      label: Exit artifacts
      description: Evidence to attach/link before closing.
      options:
        - label: "Reverse conversion pipeline code and test results"
        - label: "Updated Plan/Preview engine supporting reverse flows"
        - label: "User documentation for `.af→.met` conversion and overwrite prompts"
        - label: "Test report demonstrating acceptance tests for this milestone"
        - label: "Roadmap change log updated if scope changed"

  - type: textarea
    id: blockers
    attributes:
      label: Blockers / Risks
      description: List concrete blockers, risks, and mitigation steps.
      placeholder: |
        - Blocker:
        - Risk:
        - Mitigation:
    validations:
      required: false

  - type: textarea
    id: pr_links
    attributes:
      label: PR links / commits
      description: Add links to PRs or commit SHAs implementing this milestone work.
      placeholder: |
        - PR:
        - Commit:
    validations:
      required: false