name: "M4 — Mapping Repair & Relink"
description: "Implement workflows to repair mapping fingerprint drift and relink entries when .af files are moved or renamed."
title: "M4 — Mapping Repair & Relink"
labels:
  - "milestone:M4"
  - "area:repair"
  - "area:relink"
  - "tests"
  - "docs"
body:
  - type: markdown
    attributes:
      value: |
        ## Goal
        Provide workflows to repair the mapping file when the fingerprint of `MET_SOURCE_DIR` drifts and to relink mapping entries when `.af` files are moved or renamed.  
        This milestone detects fingerprint mismatches, offers a Repair Mapping UI that recomputes the fingerprint, rescans
        `MET_SOURCE_DIR`, deterministically activates or retires items and writes `mapping.yaml` transactionally.  It also offers a
        Relink workflow to match missing entries by size and hash or allow users to locate or skip missing `.af` files within `AF_REPO_DIR`.
        Plan/Preview output should incorporate these repair and relink outcomes.

  - type: textarea
    id: context
    attributes:
      label: Context / Links
      description: Link spec sections, roadmap sections, prior issues/PRs, and any relevant notes.
      placeholder: |
        - Spec: docs/spec.final.md§8.4,§8.5,§7.3
        - Roadmap: docs/roadmap.md§5.1–5.11 (M4)
        - Related: <ISSUE_OR_PR_LINKS>
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Scope

        ### In
        - **Fingerprint drift detection**: at run start, detect when the `MET_SOURCE_ROOT_FINGERPRINT` no longer matches the stored fingerprint; block conversion until repair is performed.
        - **Repair Mapping**: compute a new fingerprint, rescan `MET_SOURCE_DIR`, deterministically set item states to `active` or `retired`, update `MET_REL` and retire timestamps, enforce invariants and write `mapping.yaml` transactionally; allow cancellation with no writes.
        - **Relink workflow**: when referenced `AF_REL` is missing or unmapped `.af` files exist, search by size and hash; if exactly one match, update `AF_REL`; otherwise prompt the user to locate within `AF_REPO_DIR` or skip; restrict location selection to `AF_REPO_DIR`.
        - **Plan/Preview integration**: update the Plan/Preview engine to include Repair and Relink outcomes so users can review changes before committing.

        ### Out
        - Conversion pipelines (`.met→.af` and `.af→.met`).
        - Bootstrapping and logging hardening.
        - Modifying naming or sanitisation algorithms.

  - type: checkboxes
    id: execution
    attributes:
      label: Execution checklist
      description: Check as implementation items are completed.
      options:
        - label: "Detect fingerprint drift at run start and block conversions until repair is offered"
        - label: "Implement Repair Mapping workflow: recompute fingerprint, rescan `MET_SOURCE_DIR`, set item states to active/retired, update `MET_REL`/retire timestamps and write `mapping.yaml` transactionally"
        - label: "Support cancellation of Repair Mapping with no writes"
        - label: "Implement Relink workflow: search for missing entries by size/hash; if one match update `AF_REL`; otherwise prompt user to locate within `AF_REPO_DIR` or skip"
        - label: "Restrict locate selections to `AF_REPO_DIR` and enforce invariants and deterministic naming when updating entries"
        - label: "Update Plan/Preview engine to display repair and relink outcomes"
        - label: "Add unit/integration tests covering drift detection, repair mapping determinism and transactional writes, relink matching and UI prompts"

  - type: checkboxes
    id: dod
    attributes:
      label: Definition of Done
      description: Check as items are satisfied.
      options:
        - label: "Repair Mapping detects fingerprint drift, shows preview of activations/retirements and writes updated `mapping.yaml` only on approval"
        - label: "Relink workflow matches missing entries by size/hash and restricts locate selections to `AF_REPO_DIR`; user can choose locate or skip"
        - label: "Cancelling Repair Mapping or Relink produces no writes"
        - label: "Plan/Preview includes repair and relink outcomes"
        - label: "Milestone‑scoped acceptance tests pass (AT‑0017, AT‑0018)"

  - type: checkboxes
    id: exit_artifacts
    attributes:
      label: Exit artifacts
      description: Evidence to attach/link before closing.
      options:
        - label: "Repair Mapping module code and test report"
        - label: "Relink module code and test report"
        - label: "Updated documentation describing when to repair mapping and how to use relink"
        - label: "Decision log noting activation/retirement rules and relink choices"
        - label: "Roadmap change log updated if scope changed"

  - type: textarea
    id: blockers
    attributes:
      label: Blockers / Risks
      description: List concrete blockers, risks, and mitigation steps.
      placeholder: |
        - Blocker:
        - Risk:
        - Mitigation:
    validations:
      required: false

  - type: textarea
    id: pr_links
    attributes:
      label: PR links / commits
      description: Add links to PRs or commit SHAs implementing this milestone work.
      placeholder: |
        - PR:
        - Commit:
    validations:
      required: false